import { useState, useEffect } from "react";
import Head from "next/head";

/* ═══════════════════════════ COLORS ═══════════════════════════ */
var P="#0A2E52",PM="#1A4F7A",A="#E8702A",AL="#FF8C42",T="#007B8A",TL="#00A8BC",OK="#1E7E44",OKB="#E6F4EA",WN="#C8830A",WNB="#FFF8E6",BD="#C0392B",BDB="#FDECEA",BG="#F0F4F8",CD="#FFFFFF",BR="#D8E3ED",TX="#0D1B2A",SB="#4A6174",MT="#8A9BAE",WH="#FFFFFF",GD="#D4A017",PP="#5E35B1",PPB="#EDE7F6";

/* ═══════════════════════════ DATA ═══════════════════════════ */
var HOSPITALS=[
{id:1,name:"Apollo Hospitals",city:"Chennai",state:"Tamil Nadu",tier:"Gold",score:4.8,beds:560,procs:12400,specs:["Cardiology","Oncology","Neurology"],langs:["English","Arabic","Russian"],intl:true,est:1983,desc:"India's foremost healthcare institution with JCI accreditation. Known for cardiac sciences, oncology, and organ transplantation. Serves patients from 120+ countries.",phone:"+91-44-2829-3333",email:"international@apollohospitals.com",web:"apollohospitals.com"},
{id:2,name:"Fortis Healthcare",city:"Gurugram",state:"Haryana",tier:"Silver",score:4.6,beds:340,procs:9800,specs:["Orthopedics","Cardiac Surgery","Urology"],langs:["English","French","Bengali"],intl:true,est:2001,desc:"Multi-super specialty quaternary care hospital with internationally acclaimed doctors and advanced technology for complex medical cases.",phone:"+91-124-492-1021",email:"info@fortishealthcare.com",web:"fortishealthcare.com"},
{id:3,name:"Medanta - The Medicity",city:"Gurugram",state:"Haryana",tier:"Gold",score:4.9,beds:1250,procs:18200,specs:["Liver Transplant","Cardiac","Kidney Transplant"],langs:["English","Arabic","Hindi"],intl:true,est:2009,desc:"Founded by Dr. Naresh Trehan. With 1250+ beds and 45+ super-specialty departments, one of India's largest and most advanced private hospitals.",phone:"+91-124-414-1414",email:"international@medanta.org",web:"medanta.org"},
{id:4,name:"AIIMS New Delhi",city:"New Delhi",state:"Delhi",tier:"Gold",score:4.7,beds:2478,procs:22000,specs:["Neurosurgery","Pediatrics","AYUSH"],langs:["English","Hindi"],intl:false,est:1956,desc:"India's premier government medical institution. Known for cutting-edge research and affordable tertiary care across all medical disciplines.",phone:"+91-11-2658-8500",email:"director@aiims.edu",web:"aiims.edu"},
{id:5,name:"Kokilaben Hospital",city:"Mumbai",state:"Maharashtra",tier:"Gold",score:4.8,beds:750,procs:15600,specs:["Oncology","Robotic Surgery","BMT"],langs:["English","Arabic","Gujarati"],intl:true,est:2009,desc:"Leading tertiary care facility in Mumbai known for oncology excellence, robotic surgery precision, and one of India's best bone marrow transplant centers.",phone:"+91-22-3099-9999",email:"international@kokilabenhospital.com",web:"kokilabenhospital.com"}
];
var MVTFS=[
{id:1,name:"Wellness Bridge",city:"Mumbai",score:4.9,cases:5600,since:2012,langs:["English","Arabic","Urdu","Hindi"],specs:["AYUSH","Wellness","Cardiac","Oncology"],services:["Visa Assistance","Airport Pickup","Hospital Coordination","Accommodation","Interpreter","Post-treatment Follow-up"],cert:"NABH-MVTF-2890",desc:"Premier NABH-certified facilitator with 12+ years handling 5,600+ international patient cases across cardiac, AYUSH, and wellness treatments."},
{id:2,name:"IndiaHealth Connect",city:"New Delhi",score:4.7,cases:3400,since:2015,langs:["English","Arabic","Russian"],specs:["Cardiac","Oncology","Transplant"],services:["End-to-end Coordination","Visa Support","Translation","Insurance Claims"],cert:"NABH-MVTF-2341",desc:"Leading medical tourism facilitator based in New Delhi, specializing in cardiac and oncology for Middle East and African patients."},
{id:3,name:"MedJourney India",city:"Chennai",score:4.5,cases:2100,since:2017,langs:["English","French","Tamil"],specs:["Orthopedics","Transplant","Spine Surgery"],services:["Hospital Selection","Cost Negotiation","Travel Arrangement","Recovery Monitoring"],cert:"NABH-MVTF-1892",desc:"Chennai-based MVTF with deep expertise in orthopedics and organ transplant facilitation for francophone African nations."},
{id:4,name:"CureIndia Partners",city:"Bengaluru",score:4.6,cases:1200,since:2019,langs:["English","Sinhala","Bangla"],specs:["Fertility","Neurology","Pediatrics"],services:["Virtual Consult Setup","Visa Assistance","Accommodation","Local Transport"],cert:"NABH-MVTF-3110",desc:"Bengaluru-based facilitator specializing in fertility treatments and neurology, primarily serving South Asian patients."}
];
var PARTNERS=[
{id:1,name:"Gulf Med Partners",country:"UAE",city:"Dubai",type:"Overseas MVTF",patients:890,langs:["Arabic","English"],specs:["Cardiac","Oncology","Orthopedics"],verified:true,desc:"Leading UAE-based medical tourism facilitator connecting Gulf patients with top Indian hospitals."},
{id:2,name:"AfroHealth Tourism",country:"Nigeria",city:"Lagos",type:"Travel Agent",patients:340,langs:["English","Yoruba"],specs:["Oncology","Transplant"],verified:true,desc:"Nigerian medical tourism agency facilitating patient travel for advanced treatments."},
{id:3,name:"Dr. Rajan Mehta",country:"Canada",city:"Toronto",type:"Referring Doctor",patients:120,langs:["English","Hindi"],specs:["Cardiology","Neurology"],verified:true,desc:"Canadian physician referring complex cardiology and neurology cases to India."},
{id:4,name:"SriLanka Med Tours",country:"Sri Lanka",city:"Colombo",type:"Travel Agent",patients:560,langs:["English","Sinhala","Tamil"],specs:["Cardiac","Orthopedics","Dental"],verified:true,desc:"Sri Lankan agency with strong Indian hospital partnerships since 2014."}
];
var ACCOMMODATION=[
{id:1,name:"Medstay Suites",city:"Chennai",type:"Serviced Apartment",near:"Apollo Hospitals",dist:"0.3 km",amenities:["Wheelchair Access","Diet Support","Attendant Room","Nurse Call"],price:"3,500-6,000",rating:4.6},
{id:2,name:"Recovery Haven",city:"Gurugram",type:"Recovery Home",near:"Medanta",dist:"0.8 km",amenities:["24hr Nursing","Diet Kitchen","Physiotherapy","Transport"],price:"5,000-9,000",rating:4.8},
{id:3,name:"Healing Residency",city:"Mumbai",type:"Hotel",near:"Kokilaben Hospital",dist:"1.2 km",amenities:["Wheelchair Access","Interpreter","Halal Food","Medical Concierge"],price:"4,500-7,500",rating:4.4}
];
var ALLIED=[
{id:1,name:"FX India Healthcare",cat:"Forex",icon:"\uD83D\uDCB1",services:["Currency Exchange","Wire Transfer","Travel Cards"],rating:4.5},
{id:2,name:"Global Health Insure",cat:"Insurance",icon:"\uD83D\uDEE1",services:["Medical Travel Insurance","Emergency Cover","Repatriation"],rating:4.7},
{id:3,name:"MedTranslate Pro",cat:"Translator",icon:"\uD83C\uDF10",services:["Arabic","Russian","French","Sinhala","Swahili"],rating:4.9},
{id:4,name:"Atharva Wellness",cat:"AYUSH",icon:"\uD83C\uDF3F",services:["Ayurveda","Yoga Therapy","Panchakarma"],rating:4.8},
{id:5,name:"Recovery Wellness Spa",cat:"Wellness",icon:"\uD83D\uDC86",services:["Post-op Rehab","Physiotherapy","Meditation"],rating:4.6}
];
var TREATMENTS=[
{id:1,name:"Coronary Bypass (CABG)",cat:"Allopathic",spec:"Cardiac Surgery",days:7,recovery:42,price:"3-8 Lakh",success:"97.5%"},
{id:2,name:"Hip Replacement",cat:"Allopathic",spec:"Orthopedics",days:5,recovery:60,price:"2.5-6 Lakh",success:"95%"},
{id:3,name:"Liver Transplant",cat:"Allopathic",spec:"Transplant",days:21,recovery:90,price:"15-35 Lakh",success:"88%"},
{id:4,name:"Chemotherapy",cat:"Allopathic",spec:"Oncology",days:3,recovery:14,price:"0.5-3 Lakh/cycle",success:"70%"},
{id:5,name:"Panchakarma Therapy",cat:"AYUSH",spec:"Ayurveda",days:14,recovery:7,price:"0.3-1.5 Lakh",success:"92%"},
{id:6,name:"IVF Treatment",cat:"Allopathic",spec:"Fertility",days:14,recovery:14,price:"1-3 Lakh",success:"45%"},
{id:7,name:"Dental Implants",cat:"Allopathic",spec:"Dental",days:2,recovery:14,price:"0.25-1.5 Lakh",success:"96%"}
];
var GRIEVANCES=[
{id:"GRV-2025-0891",date:"12 Nov 2024",against:"Fortis Healthcare",status:"Resolved",cat:"Hospital",summary:"Miscommunication on treatment cost estimate",resolution:"Cost sheet corrected and re-issued. Refund of overpayment processed."},
{id:"GRV-2025-0674",date:"03 Oct 2024",against:"IndiaHealth Connect",status:"In Progress",cat:"MVTF",summary:"Delayed visa support documentation leading to appointment cancellation"},
{id:"GRV-2025-1024",date:"01 Dec 2024",against:"Recovery Haven",status:"Under Review",cat:"Accommodation",summary:"Accommodation standards significantly below what was advertised online"}
];
var REFERRALS=[
{id:"REF-2025-000042",patient:"Ahmed Al-Rashid",country:"UAE",condition:"Triple vessel coronary artery disease requiring CABG",status:"Estimates Received",priority:"urgent",date:"10 Jan 2025",estimates:2,mvtf:"Wellness Bridge",hospital:"Apollo Hospitals"},
{id:"REF-2025-000039",patient:"Grace Okonkwo",country:"Nigeria",condition:"Stage 2 breast cancer requiring oncology evaluation",status:"Assigned to MVTF",priority:"normal",date:"08 Jan 2025",estimates:0,mvtf:"IndiaHealth Connect",hospital:null},
{id:"REF-2025-000035",patient:"Dinesh Perera",country:"Sri Lanka",condition:"Total hip replacement bilateral",status:"Completed",priority:"normal",date:"20 Dec 2024",estimates:3,mvtf:"MedJourney India",hospital:"Medanta"}
];
var ONBOARD=[
{id:"APP-2025-0441",name:"MedLink Arabia",type:"Overseas Partner",loc:"Saudi Arabia",date:"05 Jan 2025",status:"Pending",docs:4},
{id:"APP-2025-0442",name:"Nairobi Health Tours",type:"Overseas Partner",loc:"Kenya",date:"06 Jan 2025",status:"Pending",docs:3},
{id:"APP-2025-0443",name:"HealthBridge India",type:"Indian MVTF",loc:"Pune, India",date:"07 Jan 2025",status:"Under Review",docs:6},
{id:"APP-2025-0444",name:"Lotus Multispecialty Hospital",type:"Hospital",loc:"Jaipur, India",date:"08 Jan 2025",status:"Pending",docs:8}
];

/* ═══════════════════════════ UI HELPERS ═══════════════════════════ */
function B({children,c,bg,dot}){return React.createElement("span",{style:{display:"inline-flex",alignItems:"center",gap:3,padding:"3px 10px",borderRadius:999,background:bg||BG,fontSize:10,fontWeight:700,color:c||SB}},dot?React.createElement("span",{style:{width:5,height:5,borderRadius:"50%",background:c||SB}}):null,children)}
function TB({t}){return t==="Gold"?B({children:"NABH Gold",c:WN,bg:WNB,dot:true}):B({children:"NABH Silver",c:MT,bg:"#F0F4F8",dot:true})}
function SB2({s}){var m={"Resolved":[OK,OKB],"In Progress":[WN,WNB],"Under Review":[PP,PPB],"Pending":["#1565C0","#E3F2FD"],"Approved":[OK,OKB],"Estimates Received":[A,"#FFF0E6"],"Assigned to MVTF":[PP,PPB],"Completed":[OK,OKB]};var r=m[s]||[SB,BG];return B({children:s,c:r[0],bg:r[1]})}
function Stars({v,sz}){var size=sz||12;return React.createElement("span",{style:{display:"flex",gap:1,alignItems:"center"}},[1,2,3,4,5].map(function(i){return React.createElement("span",{key:i,style:{fontSize:size,color:i<=Math.round(v)?GD:BR}},"\u2605")}),React.createElement("span",{style:{fontSize:11,fontWeight:700,marginLeft:4,color:TX}},v))}
function Card({children,s,onClick}){return React.createElement("div",{onClick:onClick,style:Object.assign({background:CD,borderRadius:16,boxShadow:"0 2px 12px rgba(10,46,82,0.06)",padding:16,marginBottom:12,border:"1px solid "+BR,cursor:onClick?"pointer":"default",transition:"all 0.15s"},s||{})},children)}
function Btn({children,c,bg,full,sm,onClick,s}){return React.createElement("button",{onClick:onClick,style:Object.assign({padding:sm?"8px 14px":"12px 20px",borderRadius:12,background:bg||A,color:c||WH,fontWeight:700,fontSize:sm?11:14,border:"none",cursor:"pointer",width:full?"100%":undefined,display:"inline-flex",alignItems:"center",justifyContent:"center",gap:6,transition:"all 0.15s"},s||{})},children)}
function Inp({label,placeholder,value,onChange,type,rows}){return React.createElement("div",{style:{marginBottom:14}},label?React.createElement("label",{style:{fontSize:11,fontWeight:600,color:SB,display:"block",marginBottom:5}},label):null,rows?React.createElement("textarea",{placeholder:placeholder,value:value,onChange:function(e){if(onChange)onChange(e.target.value)},rows:rows,style:{width:"100%",padding:"10px 14px",borderRadius:12,border:"1.5px solid "+BR,fontSize:13,outline:"none",resize:"none",boxSizing:"border-box",fontFamily:"inherit"}}):React.createElement("input",{type:type||"text",placeholder:placeholder,value:value,onChange:function(e){if(onChange)onChange(e.target.value)},style:{width:"100%",padding:"10px 14px",borderRadius:12,border:"1.5px solid "+BR,fontSize:13,outline:"none",boxSizing:"border-box",fontFamily:"inherit"}}))}
function Stat({label,value,icon,sub,color}){return React.createElement("div",{style:{flex:"1 1 calc(50% - 6px)",background:CD,borderRadius:12,padding:"14px 12px",border:"1px solid "+BR}},React.createElement("div",{style:{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}},React.createElement("div",null,React.createElement("div",{style:{fontSize:22,fontWeight:800,color:TX}},value),React.createElement("div",{style:{fontSize:10,color:MT,marginTop:2}},label),sub?React.createElement("div",{style:{fontSize:9,color:color||OK,marginTop:2,fontWeight:600}},sub):null),React.createElement("div",{style:{width:34,height:34,borderRadius:10,background:(color||T)+"15",display:"flex",alignItems:"center",justifyContent:"center",fontSize:17}},icon)))}
function Sec({title,sub,action,onAction}){return React.createElement("div",{style:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:12,marginTop:8}},React.createElement("div",null,React.createElement("div",{style:{fontSize:17,fontWeight:800,color:TX,letterSpacing:"-0.3px"}},title),sub?React.createElement("div",{style:{fontSize:11,color:MT,marginTop:2}},sub):null),action?React.createElement("button",{onClick:onAction,style:{fontSize:11,color:A,fontWeight:700,border:"none",background:"none",cursor:"pointer"}},action):null)}
function Search({value,onChange,ph}){return React.createElement("div",{style:{position:"relative",marginBottom:12}},React.createElement("span",{style:{position:"absolute",left:14,top:"50%",transform:"translateY(-50%)",fontSize:15,color:MT}},"\uD83D\uDD0D"),React.createElement("input",{value:value,onChange:function(e){onChange(e.target.value)},placeholder:ph||"Search...",style:{width:"100%",padding:"11px 14px 11px 40px",borderRadius:12,border:"1.5px solid "+BR,background:CD,fontSize:13,color:TX,outline:"none",boxSizing:"border-box",fontFamily:"inherit"}}))}
function Tabs({tabs,active,onChange}){return React.createElement("div",{style:{display:"flex",gap:6,marginBottom:14,overflowX:"auto",paddingBottom:4}},tabs.map(function(t){return React.createElement("button",{key:t.id,onClick:function(){onChange(t.id)},style:{padding:"7px 16px",borderRadius:999,whiteSpace:"nowrap",background:active===t.id?P:CD,color:active===t.id?WH:SB,border:"1.5px solid "+(active===t.id?P:BR),fontWeight:600,fontSize:12,cursor:"pointer",transition:"all 0.15s"}},t.label)}))}

/* ═══════════════════════════ LAYOUT ═══════════════════════════ */
function Header({title,sub}){return React.createElement("div",{style:{background:"linear-gradient(135deg,"+P+","+PM+")",padding:"24px 24px 20px"}},React.createElement("div",{style:{fontSize:22,fontWeight:800,color:WH}},title),sub?React.createElement("div",{style:{fontSize:12,color:"rgba(255,255,255,0.5)",marginTop:4}},sub):null)}
function Page({header,children}){return React.createElement("div",{style:{height:"100%",display:"flex",flexDirection:"column",background:BG}},header,React.createElement("div",{style:{flex:1,overflow:"auto",padding:"16px 20px 24px"}},children))}

/* ═══════════════════════════ SCREENS ═══════════════════════════ */

function LoginScreen({onLogin}){
  var rs=useState("splash"),step=rs[0],setStep=rs[1];
  var rl=useState(""),role=rl[0],setRole=rl[1];
  var ld=useState(false),loading=ld[0],setLoading=ld[1];
  var roles=[{id:"overseas",l:"Overseas Partner",i:"\uD83C\uDF0D",d:"Travel agents, overseas MVTFs, referring doctors"},{id:"mvtf",l:"Indian MVTF",i:"\uD83E\uDD1D",d:"NABH-certified Indian facilitators"},{id:"hospital",l:"Hospital",i:"\uD83C\uDFE5",d:"NABH-accredited hospitals"},{id:"admin",l:"QCI / NABH Admin",i:"\uD83D\uDEE1\uFE0F",d:"Platform governance & oversight"}];
  var go=function(){setLoading(true);setTimeout(function(){setLoading(false);onLogin(role||"overseas")},800)};

  if(step==="splash")return React.createElement("div",{style:{height:"100%",display:"flex",flexDirection:"column",background:"linear-gradient(160deg,#071E38 0%,"+P+" 50%,"+PM+" 100%)",position:"relative",overflow:"hidden",alignItems:"center",justifyContent:"center",padding:40}},React.createElement("div",{style:{width:90,height:90,borderRadius:24,background:"rgba(255,255,255,0.1)",display:"flex",alignItems:"center",justifyContent:"center",marginBottom:24,border:"1px solid rgba(255,255,255,0.2)",fontSize:44}},"\uD83C\uDFE5"),React.createElement("div",{style:{fontSize:32,fontWeight:900,color:WH,textAlign:"center",letterSpacing:"-0.5px",marginBottom:8}},"Bharat Health Connect"),React.createElement("div",{style:{fontSize:14,color:"rgba(255,255,255,0.5)",textAlign:"center",lineHeight:1.6,marginBottom:8}},"India's Medical Value Tourism",React.createElement("br"),"Digital Access Platform"),React.createElement("div",{style:{marginTop:8,marginBottom:40,padding:"6px 16px",background:"rgba(232,112,42,0.2)",borderRadius:999,border:"1px solid rgba(232,112,42,0.4)"}},React.createElement("span",{style:{fontSize:11,color:AL,fontWeight:700,letterSpacing:1.5}},"GOVERNED BY QCI \u2022 NABH VERIFIED")),React.createElement("div",{style:{width:"100%",maxWidth:360}},React.createElement(Btn,{full:true,onClick:function(){setStep("role")}},"Get Started"),React.createElement("div",{style:{textAlign:"center",marginTop:14}},React.createElement("span",{onClick:function(){setStep("login")},style:{fontSize:13,color:"rgba(255,255,255,0.45)",cursor:"pointer"}},"Already registered? ",React.createElement("span",{style:{color:AL,fontWeight:700}},"Sign In")))));

  if(step==="role")return React.createElement(Page,{header:React.createElement("div",{style:{background:"linear-gradient(135deg,"+P+","+PM+")",padding:"20px 24px 16px"}},React.createElement("button",{onClick:function(){setStep("splash")},style:{background:"none",border:"none",cursor:"pointer",color:"rgba(255,255,255,0.7)",fontSize:16,marginBottom:12}},"\u2190 Back"),React.createElement("div",{style:{fontSize:22,fontWeight:800,color:WH}},"Select Your Role"),React.createElement("div",{style:{fontSize:12,color:"rgba(255,255,255,0.5)",marginTop:4}},"Your credentials will be verified against the NABH registry"))},roles.map(function(r){return React.createElement("div",{key:r.id,onClick:function(){setRole(r.id);setStep("login")},style:{background:CD,borderRadius:16,padding:16,marginBottom:12,border:"1.5px solid "+BR,cursor:"pointer",display:"flex",alignItems:"center",gap:14}},React.createElement("div",{style:{width:48,height:48,borderRadius:12,background:T+"15",display:"flex",alignItems:"center",justifyContent:"center",fontSize:24}},r.i),React.createElement("div",{style:{flex:1}},React.createElement("div",{style:{fontSize:15,fontWeight:700,color:TX}},r.l),React.createElement("div",{style:{fontSize:12,color:MT,marginTop:2}},r.d)),React.createElement("span",{style:{color:MT,fontSize:18}},"\u203A"))}));

  return React.createElement(Page,{header:React.createElement("div",{style:{background:"linear-gradient(135deg,"+P+","+PM+")",padding:"20px 24px 16px"}},React.createElement("button",{onClick:function(){setStep("role")},style:{background:"none",border:"none",cursor:"pointer",color:"rgba(255,255,255,0.7)",fontSize:16,marginBottom:12}},"\u2190 Back"),React.createElement("div",{style:{fontSize:22,fontWeight:800,color:WH}},"Welcome Back"),React.createElement("div",{style:{fontSize:12,color:"rgba(255,255,255,0.5)",marginTop:4}},"Sign in with your NABH-issued credentials"))},React.createElement(Inp,{label:"Email / NABH ID",placeholder:"e.g. admin@bharathealthconnect.in"}),React.createElement(Inp,{label:"Password",placeholder:"Enter password",type:"password"}),React.createElement("div",{style:{marginTop:4}},React.createElement(Btn,{full:true,onClick:go,bg:loading?MT:A},loading?"Verifying...":"Sign In")),React.createElement("div",{style:{marginTop:20,padding:14,borderRadius:12,background:TL+"18",border:"1px solid "+T+"33"}},React.createElement("div",{style:{fontSize:11,color:T,fontWeight:700}},"\u2728 Demo Mode"),React.createElement("div",{style:{fontSize:11,color:SB,marginTop:3}},"Click Sign In to explore as ",React.createElement("strong",null,(roles.find(function(r){return r.id===role})||{}).l||"Overseas Partner"),". All data is illustrative.")));
}

function DashboardScreen({role,nav}){
  var profiles={overseas:{n:"Gulf Med Partners",bd:"NABH Assured Partner",i:"\uD83C\uDF0D"},mvtf:{n:"Wellness Bridge",bd:"NABH Certified MVTF",i:"\uD83E\uDD1D"},hospital:{n:"Apollo Hospitals",bd:"NABH Gold Hospital",i:"\uD83C\uDFE5"},admin:{n:"QCI Admin",bd:"Platform Administrator",i:"\uD83D\uDEE1\uFE0F"}};
  var p=profiles[role]||profiles.overseas;
  var qa=role==="admin"?[{id:"onboarding",i:"\uD83D\uDCCB",l:"Onboarding Queue",ct:4,cl:A},{id:"grievances",i:"\u26A0\uFE0F",l:"Grievance Queue",ct:3,cl:BD},{id:"analytics",i:"\uD83D\uDCC8",l:"Analytics",cl:T},{id:"hospitals",i:"\uD83C\uDFE5",l:"Hospital Directory",cl:OK}]:[{id:"hospitals",i:"\uD83C\uDFE5",l:"Find Hospitals",cl:PM},{id:"mvtfs",i:"\uD83E\uDD1D",l:"Find MVTFs",cl:T},{id:"referrals",i:"\uD83D\uDCCB",l:"Referrals",cl:A},{id:"grievances",i:"\u26A0\uFE0F",l:"Raise SoS",cl:BD}];

  return React.createElement(Page,{header:React.createElement("div",{style:{background:"linear-gradient(135deg,"+P+","+PM+")",padding:"20px 24px 28px"}},React.createElement("div",{style:{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}},React.createElement("div",null,React.createElement("div",{style:{fontSize:12,color:"rgba(255,255,255,0.5)",marginBottom:4}},"Good morning \uD83D\uDC4B"),React.createElement("div",{style:{fontSize:20,fontWeight:800,color:WH}},p.n),React.createElement("div",{style:{marginTop:6,display:"flex",gap:6,alignItems:"center"}},React.createElement("div",{style:{width:6,height:6,borderRadius:"50%",background:"#4CAF50"}}),React.createElement("span",{style:{fontSize:11,color:"rgba(255,255,255,0.55)"}},p.bd))),React.createElement("div",{style:{width:44,height:44,borderRadius:"50%",background:"rgba(232,112,42,0.3)",border:"2px solid rgba(232,112,42,0.6)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20}},p.i)))},
  React.createElement("div",{style:{background:"linear-gradient(135deg,"+A+",#c85a1a)",borderRadius:16,padding:"18px 22px",marginTop:-14,marginBottom:20,boxShadow:"0 4px 20px "+A+"55"}},React.createElement("div",{style:{display:"flex",justifyContent:"space-between",alignItems:"center"}},React.createElement("div",null,React.createElement("div",{style:{fontSize:10,color:"rgba(255,255,255,0.65)",marginBottom:4}},"QCI TRUST SCORE"),React.createElement("div",{style:{display:"flex",alignItems:"baseline",gap:6}},React.createElement("span",{style:{fontSize:36,fontWeight:900,color:WH}},"4.8"),React.createElement("span",{style:{fontSize:13,color:"rgba(255,255,255,0.6)"}},"/ 5.0")),React.createElement(Stars,{v:4.8,sz:13})),React.createElement("div",{style:{width:64,height:64,borderRadius:"50%",background:"rgba(255,255,255,0.15)",display:"flex",alignItems:"center",justifyContent:"center",border:"2px solid rgba(255,255,255,0.25)",fontSize:30}},"\uD83C\uDFC5"))),
  React.createElement(Sec,{title:"Quick Access"}),
  React.createElement("div",{style:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:24}},qa.map(function(a){return React.createElement("button",{key:a.id,onClick:function(){nav(a.id)},style:{background:CD,borderRadius:16,padding:"18px 14px",border:"1.5px solid "+BR,cursor:"pointer",textAlign:"left",position:"relative"}},React.createElement("div",{style:{width:40,height:40,borderRadius:10,background:a.cl+"15",display:"flex",alignItems:"center",justifyContent:"center",marginBottom:10,fontSize:20}},a.i),React.createElement("div",{style:{fontSize:13,fontWeight:700,color:TX}},a.l),a.ct?React.createElement("div",{style:{position:"absolute",top:10,right:10,width:20,height:20,borderRadius:"50%",background:a.cl,display:"flex",alignItems:"center",justifyContent:"center"}},React.createElement("span",{style:{fontSize:10,fontWeight:800,color:WH}},a.ct)):null)})),
  React.createElement(Sec,{title:role==="admin"?"Platform Overview":"Your Network"}),
  React.createElement("div",{style:{display:"flex",flexWrap:"wrap",gap:10,marginBottom:20}},role==="admin"?[React.createElement(Stat,{key:"s1",label:"Total Stakeholders",value:"4,847",icon:"\uD83D\uDC65",color:T,sub:"\u2191 234 this month"}),React.createElement(Stat,{key:"s2",label:"NABH Hospitals",value:"2,847",icon:"\uD83C\uDFE5",color:PM}),React.createElement(Stat,{key:"s3",label:"Open Grievances",value:"12",icon:"\u26A0\uFE0F",color:BD,sub:"3 critical"}),React.createElement(Stat,{key:"s4",label:"Pending Approvals",value:"4",icon:"\uD83D\uDCCB",color:WN})]:[React.createElement(Stat,{key:"s1",label:"Verified Hospitals",value:"2,847",icon:"\uD83C\uDFE5",color:T,sub:"\u2191 124 this month"}),React.createElement(Stat,{key:"s2",label:"Active Partners",value:"1,293",icon:"\uD83E\uDD1D",color:PM,sub:"\u2191 56 this month"}),React.createElement(Stat,{key:"s3",label:"Your Connections",value:"34",icon:"\uD83C\uDF0D",color:OK}),React.createElement(Stat,{key:"s4",label:"Open Tickets",value:"2",icon:"\u26A0\uFE0F",color:WN,sub:"SoS Active"})]),
  role!=="admin"?[React.createElement(Sec,{key:"ht",title:"Top Rated Hospitals",action:"View All",onAction:function(){nav("hospitals")}}),HOSPITALS.slice(0,3).map(function(h){return React.createElement(Card,{key:h.id,onClick:function(){nav("hospital-"+h.id)}},React.createElement("div",{style:{display:"flex",gap:12}},React.createElement("div",{style:{width:48,height:48,borderRadius:12,background:TL+"18",display:"flex",alignItems:"center",justifyContent:"center",fontSize:24,flexShrink:0}},"\uD83C\uDFE5"),React.createElement("div",{style:{flex:1,minWidth:0}},React.createElement("div",{style:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:4,flexWrap:"wrap"}},React.createElement("div",{style:{fontSize:14,fontWeight:700,color:TX}},h.name),React.createElement(TB,{t:h.tier})),React.createElement("div",{style:{fontSize:11,color:MT,marginTop:3}},"\uD83D\uDCCD "+h.city+", "+h.state+" \u2022 "+h.beds+" beds"),React.createElement("div",{style:{marginTop:4}},React.createElement(Stars,{v:h.score})))))})]:null);
}

function HospitalListScreen({nav}){
  var qs=useState(""),q=qs[0],setQ=qs[1];
  var fs=useState("All"),f=fs[0],setF=fs[1];
  var tabs=[{id:"All",label:"All"},{id:"Gold",label:"Gold"},{id:"Silver",label:"Silver"},{id:"Cardiac",label:"Cardiac"},{id:"Oncology",label:"Oncology"},{id:"AYUSH",label:"AYUSH"}];
  var flt=HOSPITALS.filter(function(h){var m=h.name.toLowerCase().indexOf(q.toLowerCase())>=0||h.city.toLowerCase().indexOf(q.toLowerCase())>=0||h.specs.some(function(s){return s.toLowerCase().indexOf(q.toLowerCase())>=0});if(f==="All")return m;if(f==="Gold")return m&&h.tier==="Gold";if(f==="Silver")return m&&h.tier==="Silver";return m&&h.specs.some(function(s){return s.indexOf(f)>=0})});
  return React.createElement(Page,{header:React.createElement(Header,{title:"Hospital Directory",sub:HOSPITALS.length+" NABH-verified hospitals across India"})},React.createElement(Search,{value:q,onChange:setQ,ph:"Search hospitals, specialties, cities..."}),React.createElement(Tabs,{tabs:tabs,active:f,onChange:setF}),flt.map(function(h){return React.createElement(Card,{key:h.id,onClick:function(){nav("hospital-"+h.id)}},React.createElement("div",{style:{display:"flex",gap:12}},React.createElement("div",{style:{width:52,height:52,borderRadius:12,background:TL+"18",display:"flex",alignItems:"center",justifyContent:"center",fontSize:26,flexShrink:0}},"\uD83C\uDFE5"),React.createElement("div",{style:{flex:1,minWidth:0}},React.createElement("div",{style:{display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:4}},React.createElement("div",{style:{fontSize:15,fontWeight:700,color:TX}},h.name),React.createElement(TB,{t:h.tier})),React.createElement("div",{style:{fontSize:11,color:MT,marginTop:3}},"\uD83D\uDCCD "+h.city+", "+h.state+" \u2022 "+h.beds+" beds"),React.createElement("div",{style:{display:"flex",alignItems:"center",gap:6,marginTop:5}},React.createElement(Stars,{v:h.score}),React.createElement("span",{style:{fontSize:10,color:MT}},"\u2022 "+h.procs.toLocaleString()+" procedures")),React.createElement("div",{style:{display:"flex",gap:4,marginTop:7,flexWrap:"wrap"}},h.specs.slice(0,3).map(function(s){return React.createElement("span",{key:s,style:{padding:"3px 8px",borderRadius:999,background:BG,border:"1px solid "+BR,fontSize:10,color:SB}},s)})))))}));
}

function HospitalDetailScreen({id,nav}){
  var h=HOSPITALS.find(function(x){return x.id===id});
  if(!h)return React.createElement("div",null,"Not found");
  return React.createElement(Page,{header:React.createElement("div",{style:{background:"linear-gradient(135deg,"+P+","+PM+")",padding:"20px 24px 24px"}},React.createElement("button",{onClick:function(){nav("hospitals")},style:{background:"none",border:"none",cursor:"pointer",color:"rgba(255,255,255,0.7)",fontSize:14,marginBottom:10}},"\u2190 Hospitals"),React.createElement("div",{style:{fontSize:22,fontWeight:800,color:WH}},h.name),React.createElement("div",{style:{display:"flex",alignItems:"center",gap:8,marginTop:6}},React.createElement("span",{style:{fontSize:13,color:"rgba(255,255,255,0.6)"}},"\uD83D\uDCCD "+h.city+", "+h.state),React.createElement(TB,{t:h.tier})))},
  React.createElement("div",{style:{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:16}},React.createElement(Card,{s:{textAlign:"center",padding:12}},React.createElement("div",{style:{fontSize:24,fontWeight:900,color:TX}},h.score),React.createElement(Stars,{v:h.score,sz:10}),React.createElement("div",{style:{fontSize:9,color:MT,marginTop:2}},"Trust Score")),React.createElement(Card,{s:{textAlign:"center",padding:12}},React.createElement("div",{style:{fontSize:24,fontWeight:900,color:P}},h.procs.toLocaleString()),React.createElement("div",{style:{fontSize:9,color:MT,marginTop:2}},"Procedures")),React.createElement(Card,{s:{textAlign:"center",padding:12}},React.createElement("div",{style:{fontSize:24,fontWeight:900,color:TX}},h.beds),React.createElement("div",{style:{fontSize:9,color:MT,marginTop:2}},"Beds"),React.createElement("div",{style:{fontSize:9,color:MT}},"Est. "+h.est))),
  React.createElement(Card,null,React.createElement("div",{style:{fontSize:13,color:SB,lineHeight:1.7}},h.desc)),
  React.createElement(Sec,{title:"Specialties"}),React.createElement("div",{style:{display:"flex",flexWrap:"wrap",gap:6,marginBottom:16}},h.specs.map(function(s){return React.createElement("span",{key:s,style:{padding:"6px 14px",borderRadius:999,background:TL+"18",fontSize:12,color:T,fontWeight:600}},s)})),
  React.createElement(Sec,{title:"Languages"}),React.createElement("div",{style:{display:"flex",flexWrap:"wrap",gap:6,marginBottom:16}},h.langs.map(function(l){return React.createElement("span",{key:l,style:{padding:"6px 14px",borderRadius:999,background:BG,border:"1px solid "+BR,fontSize:12,color:SB}},"\uD83C\uDF10 "+l)})),
  React.createElement(Sec,{title:"Contact"}),React.createElement(Card,null,React.createElement("div",{style:{fontSize:12,color:SB,lineHeight:2}},"\uD83D\uDCDE "+h.phone,React.createElement("br"),"\uD83D\uDCE7 "+h.email,React.createElement("br"),"\uD83C\uDF10 "+h.web)),
  React.createElement("div",{style:{display:"flex",gap:10,marginTop:8}},React.createElement(Btn,{full:true},"\uD83D\uDCDE Connect"),React.createElement(Btn,{full:true,bg:CD,c:P,s:{border:"2px solid "+P,boxShadow:"none"}},"\u2709\uFE0F Enquire")));
}

function MVTFScreen({nav}){var qs=useState(""),q=qs[0],setQ=qs[1];return React.createElement(Page,{header:React.createElement(Header,{title:"MVTF Directory",sub:"NABH-certified Indian Medical Value Travel Facilitators"})},React.createElement(Search,{value:q,onChange:setQ,ph:"Search facilitators..."}),MVTFS.filter(function(m){return m.name.toLowerCase().indexOf(q.toLowerCase())>=0||m.city.toLowerCase().indexOf(q.toLowerCase())>=0}).map(function(m){return React.createElement(Card,{key:m.id},React.createElement("div",{style:{display:"flex",gap:12}},React.createElement("div",{style:{width:48,height:48,borderRadius:"50%",background:PM+"18",display:"flex",alignItems:"center",justifyContent:"center",fontSize:22,flexShrink:0}},"\uD83E\uDD1D"),React.createElement("div",{style:{flex:1}},React.createElement("div",{style:{display:"flex",justifyContent:"space-between"}},React.createElement("div",{style:{fontSize:14,fontWeight:700,color:TX}},m.name),React.createElement(Stars,{v:m.score})),React.createElement("div",{style:{fontSize:11,color:MT,marginTop:3}},"\uD83D\uDCCD "+m.city+" \u2022 Since "+m.since+" \u2022 "+m.cases.toLocaleString()+" cases"),React.createElement("div",{style:{fontSize:11,color:MT,marginTop:2}},m.cert),React.createElement("div",{style:{display:"flex",gap:4,marginTop:6,flexWrap:"wrap"}},m.langs.map(function(l){return React.createElement("span",{key:l,style:{padding:"2px 7px",borderRadius:999,background:BG,border:"1px solid "+BR,fontSize:9}},"\uD83C\uDF10 "+l)})),React.createElement("div",{style:{display:"flex",gap:4,marginTop:4,flexWrap:"wrap"}},m.specs.map(function(s){return React.createElement("span",{key:s,style:{padding:"2px 7px",borderRadius:999,background:T+"15",fontSize:9,color:T,fontWeight:600}},s)})),React.createElement("div",{style:{display:"flex",gap:6,marginTop:10}},React.createElement(Btn,{sm:true},"Connect"),React.createElement(Btn,{sm:true,bg:CD,c:P,s:{border:"1px solid "+P,boxShadow:"none"}},"View Profile")))))}));}

function PartnerScreen(){var qs=useState(""),q=qs[0],setQ=qs[1];return React.createElement(Page,{header:React.createElement(Header,{title:"Overseas Partners",sub:"Verified overseas MVTFs, travel agents, and referring doctors"})},React.createElement(Search,{value:q,onChange:setQ,ph:"Search by name, country..."}),PARTNERS.filter(function(p){return p.name.toLowerCase().indexOf(q.toLowerCase())>=0||p.country.toLowerCase().indexOf(q.toLowerCase())>=0}).map(function(p){return React.createElement(Card,{key:p.id},React.createElement("div",{style:{display:"flex",gap:12}},React.createElement("div",{style:{width:48,height:48,borderRadius:"50%",background:TL+"18",display:"flex",alignItems:"center",justifyContent:"center",fontSize:22,flexShrink:0}},"\uD83C\uDF0D"),React.createElement("div",{style:{flex:1}},React.createElement("div",{style:{display:"flex",justifyContent:"space-between"}},React.createElement("div",{style:{fontSize:14,fontWeight:700,color:TX}},p.name),p.verified?React.createElement(B,{c:OK,bg:OKB},"\u2713 Verified"):null),React.createElement("div",{style:{fontSize:11,color:MT,marginTop:3}},"\uD83C\uDF10 "+p.country+" \u2022 "+p.type+" \u2022 "+p.patients+" patients referred"),React.createElement("div",{style:{fontSize:11,color:MT,marginTop:4}},p.desc),React.createElement("div",{style:{marginTop:8}},React.createElement(Btn,{sm:true},"Connect")))))}));}

function ReferralScreen(){return React.createElement(Page,{header:React.createElement(Header,{title:"Referrals",sub:"Patient referral management"})},React.createElement(Btn,{full:true,s:{marginBottom:20}},"+ Create New Referral"),React.createElement(Sec,{title:"Active Referrals",sub:REFERRALS.length+" total"}),REFERRALS.map(function(r){return React.createElement(Card,{key:r.id},React.createElement("div",{style:{display:"flex",justifyContent:"space-between",marginBottom:8}},React.createElement("span",{style:{fontSize:12,fontWeight:700,color:P}},r.id),React.createElement(SB2,{s:r.status})),React.createElement("div",{style:{fontSize:14,fontWeight:700,color:TX,marginBottom:4}},r.patient),React.createElement("div",{style:{fontSize:12,color:SB,marginBottom:6}},r.condition),React.createElement("div",{style:{display:"flex",alignItems:"center",gap:8,fontSize:11,color:MT,flexWrap:"wrap"}},React.createElement("span",null,"\uD83C\uDF0D "+r.country),React.createElement("span",null,"\uD83D\uDCC5 "+r.date),r.priority==="urgent"?React.createElement(B,{c:BD,bg:BDB},"Urgent"):null,r.mvtf?React.createElement("span",null,"\uD83E\uDD1D "+r.mvtf):null,r.estimates>0?React.createElement("span",null,"\uD83D\uDCCA "+r.estimates+" estimates"):null))}));}

function GrievanceScreen(){var vs=useState("list"),v=vs[0],setV=vs[1];var ds=useState(false),done=ds[0],setDone=ds[1];
if(done)return React.createElement("div",{style:{height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:40,background:BG}},React.createElement("div",{style:{width:80,height:80,borderRadius:"50%",background:OKB,display:"flex",alignItems:"center",justifyContent:"center",marginBottom:20,fontSize:36}},"\u2705"),React.createElement("div",{style:{fontSize:24,fontWeight:800,color:TX,marginBottom:8}},"Complaint Submitted"),React.createElement("div",{style:{fontSize:13,color:SB,marginBottom:6}},"Your ticket has been raised with QCI/NABH"),React.createElement("div",{style:{padding:"10px 24px",borderRadius:14,background:CD,border:"2px solid "+BR,marginBottom:24}},React.createElement("span",{style:{fontSize:16,fontWeight:800,color:P}},"GRV-2025-1025")),React.createElement(Btn,{onClick:function(){setDone(false);setV("list")}},"Back to Grievances"));
if(v==="new")return React.createElement(Page,{header:React.createElement("div",{style:{background:"linear-gradient(135deg,"+BD+",#8B0000)",padding:"20px 24px 20px"}},React.createElement("button",{onClick:function(){setV("list")},style:{background:"none",border:"none",cursor:"pointer",color:"rgba(255,255,255,0.7)",fontSize:14,marginBottom:10}},"\u2190 Back"),React.createElement("div",{style:{fontSize:22,fontWeight:800,color:WH}},"Raise Complaint / SoS"),React.createElement("div",{style:{fontSize:12,color:"rgba(255,255,255,0.5)",marginTop:4}},"All complaints routed directly to QCI Admin"))},React.createElement("div",{style:{marginBottom:14}},React.createElement("label",{style:{fontSize:11,fontWeight:600,color:SB,display:"block",marginBottom:6}},"Category"),React.createElement("div",{style:{display:"flex",gap:8,flexWrap:"wrap"}},["Hospital","MVTF","Accommodation","Allied Service","Platform"].map(function(c){return React.createElement("button",{key:c,style:{padding:"8px 14px",borderRadius:999,border:"1.5px solid "+BR,fontSize:12,fontWeight:600,cursor:"pointer",background:CD,color:SB}},c)}))),React.createElement(Inp,{label:"Name of Entity",placeholder:"e.g. Apollo Hospitals, Mumbai"}),React.createElement(Inp,{label:"Subject",placeholder:"Brief summary of the issue"}),React.createElement(Inp,{label:"Describe the Issue",placeholder:"Describe in detail including dates, names, evidence...",rows:5}),React.createElement("div",{style:{padding:"12px 16px",borderRadius:12,background:WNB,border:"1px solid "+GD+"44",marginBottom:18}},React.createElement("div",{style:{fontSize:11,color:WN,fontWeight:600}},"\u26A0\uFE0F What happens next?"),React.createElement("div",{style:{fontSize:11,color:SB,marginTop:4,lineHeight:1.6}},"QCI Admin will review within 2 business days, assign to the concerned party, and set a resolution timeline.")),React.createElement(Btn,{full:true,bg:BD,onClick:function(){setDone(true)}},"Submit Complaint"));
return React.createElement(Page,{header:React.createElement(Header,{title:"Grievances & SoS",sub:"QCI-mediated complaint resolution"})},React.createElement(Btn,{full:true,bg:BD,onClick:function(){setV("new")},s:{marginBottom:20}},"\u26A0\uFE0F Raise New Complaint"),React.createElement(Sec,{title:"Your Tickets",sub:GRIEVANCES.length+" total"}),GRIEVANCES.map(function(g){return React.createElement(Card,{key:g.id},React.createElement("div",{style:{display:"flex",justifyContent:"space-between",marginBottom:8}},React.createElement("span",{style:{fontSize:12,fontWeight:700,color:P}},g.id),React.createElement(SB2,{s:g.status})),React.createElement("div",{style:{fontSize:14,fontWeight:600,color:TX,marginBottom:4}},g.summary),React.createElement("div",{style:{fontSize:12,color:MT,marginBottom:4}},"Against: ",React.createElement("strong",null,g.against)," \u2022 ",g.cat," \u2022 ",g.date),g.resolution?React.createElement("div",{style:{marginTop:6,padding:"8px 12px",borderRadius:10,background:OKB}},React.createElement("div",{style:{fontSize:11,color:OK,fontWeight:700}},"\u2713 Resolution: "+g.resolution)):null)}));}

function OnboardingScreen(){var is=useState(ONBOARD),items=is[0],setItems=is[1];var approve=function(id){setItems(function(p){return p.map(function(i){return i.id===id?Object.assign({},i,{status:"Approved"}):i})})};
return React.createElement(Page,{header:React.createElement(Header,{title:"Onboarding Queue",sub:items.filter(function(i){return i.status!=="Approved"}).length+" pending applications"})},items.map(function(a){return React.createElement(Card,{key:a.id},React.createElement("div",{style:{display:"flex",justifyContent:"space-between",marginBottom:8}},React.createElement("span",{style:{fontSize:11,fontWeight:700,color:P}},a.id),React.createElement(SB2,{s:a.status})),React.createElement("div",{style:{fontSize:15,fontWeight:700,color:TX}},a.name),React.createElement("div",{style:{fontSize:12,color:MT,marginTop:3}},a.type+" \u2022 "+a.loc),React.createElement("div",{style:{fontSize:11,color:MT,marginTop:2}},"Applied: "+a.date+" \u2022 "+a.docs+" documents"),a.status!=="Approved"?React.createElement("div",{style:{display:"flex",gap:8,marginTop:12}},React.createElement(Btn,{sm:true,bg:OK,onClick:function(){approve(a.id)}},"\u2713 Approve"),React.createElement(Btn,{sm:true,bg:WNB,c:WN,s:{boxShadow:"none"}},"Review"),React.createElement(Btn,{sm:true,bg:BDB,c:BD,s:{boxShadow:"none"}},"\u2717 Reject")):null)}));}

function AnalyticsScreen(){
  var bars=[{l:"Aug",v:74},{l:"Sep",v:82},{l:"Oct",v:79},{l:"Nov",v:91},{l:"Dec",v:88},{l:"Jan",v:102}];var mx=102;
  var mkts=[{c:"UAE",p:2840,pc:28,f:"\uD83C\uDDE6\uD83C\uDDEA"},{c:"Bangladesh",p:1920,pc:19,f:"\uD83C\uDDE7\uD83C\uDDE9"},{c:"Nigeria",p:1540,pc:15,f:"\uD83C\uDDF3\uD83C\uDDEC"},{c:"Sri Lanka",p:1210,pc:12,f:"\uD83C\uDDF1\uD83C\uDDF0"},{c:"Others",p:2590,pc:26,f:"\uD83C\uDF0D"}];
  return React.createElement(Page,{header:React.createElement(Header,{title:"Analytics Dashboard",sub:"QCI MVT Ecosystem Intelligence"})},React.createElement("div",{style:{display:"flex",flexWrap:"wrap",gap:10,marginBottom:20}},React.createElement(Stat,{label:"Total Patients (2024)",value:"6.5L",icon:"\uD83D\uDC65",color:T,sub:"\u2191 18% YoY"}),React.createElement(Stat,{label:"Platform Revenue",value:"$13B",icon:"\uD83D\uDCC8",color:OK,sub:"GDP Contribution"}),React.createElement(Stat,{label:"Avg Trust Score",value:"4.6",icon:"\u2B50",color:GD,sub:"\u2191 0.2 this Q"}),React.createElement(Stat,{label:"Resolution Rate",value:"87%",icon:"\u2705",color:PM,sub:"Grievance SLA"})),React.createElement(Sec,{title:"Monthly Onboardings",sub:"New verified stakeholders"}),React.createElement(Card,null,React.createElement("div",{style:{display:"flex",alignItems:"flex-end",gap:8,height:100,padding:"0 4px"}},bars.map(function(b,i){return React.createElement("div",{key:b.l,style:{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:4}},React.createElement("div",{style:{fontSize:10,fontWeight:700,color:SB}},b.v),React.createElement("div",{style:{width:"100%",height:b.v/mx*75+"px",borderRadius:"4px 4px 0 0",background:i>=4?A:PM,transition:"height 0.5s"}}),React.createElement("div",{style:{fontSize:10,color:MT}},b.l))}))),React.createElement(Sec,{title:"Top Source Markets",sub:"Patient origin countries"}),React.createElement(Card,null,mkts.map(function(m,i){return React.createElement("div",{key:m.c,style:{marginBottom:i<mkts.length-1?14:0}},React.createElement("div",{style:{display:"flex",justifyContent:"space-between",marginBottom:4}},React.createElement("span",{style:{fontSize:13,fontWeight:600,color:TX}},m.f+" "+m.c),React.createElement("span",{style:{fontSize:12,color:MT}},m.p.toLocaleString()+" ("+m.pc+"%)")),React.createElement("div",{style:{height:7,borderRadius:999,background:BG,overflow:"hidden"}},React.createElement("div",{style:{height:"100%",width:m.pc*2.5+"%",borderRadius:999,background:i===0?A:i===1?T:PM}})))})));}

function ProfileScreen({role,onLogout}){
  var profiles={overseas:{n:"Gulf Med Partners",id:"NABH-OVS-2341",lo:"UAE",ty:"Overseas MVTF",em:"contact@gulfmed.ae",i:"\uD83C\uDF0D"},mvtf:{n:"Wellness Bridge",id:"NABH-MVTF-2890",lo:"Mumbai, India",ty:"Indian MVTF",em:"info@wellnessbridge.in",i:"\uD83E\uDD1D"},hospital:{n:"Apollo Hospitals",id:"NABH-HSP-0001",lo:"Chennai, India",ty:"NABH Gold Hospital",em:"international@apollohospitals.com",i:"\uD83C\uDFE5"},admin:{n:"Priya Sharma",id:"QCI-ADMIN-007",lo:"New Delhi, India",ty:"QCI Administrator",em:"p.sharma@qcin.org",i:"\uD83D\uDEE1\uFE0F"}};
  var p=profiles[role]||profiles.overseas;
  return React.createElement(Page,{header:React.createElement("div",{style:{background:"linear-gradient(135deg,"+P+","+PM+")",padding:"28px 24px 36px",textAlign:"center"}},React.createElement("div",{style:{width:72,height:72,borderRadius:"50%",background:"rgba(255,255,255,0.15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:32,margin:"0 auto 12px",border:"3px solid rgba(255,255,255,0.25)"}},p.i),React.createElement("div",{style:{fontSize:20,fontWeight:800,color:WH}},p.n),React.createElement("div",{style:{fontSize:12,color:"rgba(255,255,255,0.5)",marginTop:4}},p.id),React.createElement("div",{style:{marginTop:8}},React.createElement(B,{c:OK,bg:OKB,dot:true},p.ty)),React.createElement("div",{style:{display:"flex",alignItems:"center",justifyContent:"center",gap:6,marginTop:10}},React.createElement(Stars,{v:4.8,sz:13}),React.createElement("span",{style:{fontSize:13,fontWeight:700,color:WH}},"Trust Score")))},
  React.createElement(Card,null,[{l:"Email",v:p.em,i:"\uD83D\uDCE7"},{l:"Location",v:p.lo,i:"\uD83D\uDCCD"},{l:"Type",v:p.ty,i:"\uD83C\uDFC5"},{l:"Member Since",v:"2018",i:"\uD83D\uDCC5"}].map(function(x,i,a){return React.createElement("div",{key:x.l,style:{display:"flex",alignItems:"center",gap:12,padding:"10px 0",borderBottom:i<a.length-1?"1px solid "+BR:"none"}},React.createElement("div",{style:{width:34,height:34,borderRadius:10,background:BG,display:"flex",alignItems:"center",justifyContent:"center",fontSize:16}},x.i),React.createElement("div",null,React.createElement("div",{style:{fontSize:10,color:MT,fontWeight:600}},x.l),React.createElement("div",{style:{fontSize:13,color:TX,fontWeight:600}},x.v)))})),
  React.createElement(Sec,{title:"Settings"}),
  ["Notification Preferences","Privacy & Data Settings","Language Settings","NABH Accreditation Details","Help & Support"].map(function(s){return React.createElement(Card,{key:s,s:{display:"flex",alignItems:"center",padding:"14px 16px",marginBottom:8,cursor:"pointer"}},React.createElement("span",{style:{flex:1,fontSize:14,fontWeight:600,color:TX}},s),React.createElement("span",{style:{color:MT}},"\u203A"))}),
  React.createElement("div",{style:{marginTop:8}},React.createElement("button",{onClick:onLogout,style:{width:"100%",padding:14,borderRadius:14,background:BDB,color:BD,fontWeight:700,fontSize:14,border:"1.5px solid "+BD+"44",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",gap:8}},"\uD83D\uDEAA Sign Out")));
}

/* ═══════════════════════════ SIDEBAR NAV ═══════════════════════════ */
function Sidebar({active,nav,role,open,onClose}){
  var items=role==="admin"?[{id:"dashboard",i:"\uD83D\uDCCA",l:"Dashboard"},{id:"hospitals",i:"\uD83C\uDFE5",l:"Hospitals"},{id:"onboarding",i:"\uD83D\uDCCB",l:"Onboarding Queue"},{id:"grievances",i:"\u26A0\uFE0F",l:"Grievances"},{id:"analytics",i:"\uD83D\uDCC8",l:"Analytics"},{id:"profile",i:"\u2699\uFE0F",l:"Settings"}]:[{id:"dashboard",i:"\uD83C\uDFE0",l:"Dashboard"},{id:"hospitals",i:"\uD83C\uDFE5",l:"Hospitals"},{id:"mvtfs",i:"\uD83E\uDD1D",l:"MVTFs"},{id:"partners",i:"\uD83C\uDF0D",l:"Partners"},{id:"referrals",i:"\uD83D\uDCCB",l:"Referrals"},{id:"grievances",i:"\u26A0\uFE0F",l:"Grievances"},{id:"profile",i:"\u2699\uFE0F",l:"Profile"}];
  return React.createElement(React.Fragment,null,open?React.createElement("div",{onClick:onClose,style:{position:"fixed",inset:0,background:"rgba(0,0,0,0.4)",zIndex:90}}):null,React.createElement("div",{style:{position:"fixed",top:0,left:0,bottom:0,width:260,background:CD,borderRight:"1px solid "+BR,zIndex:100,transform:open?"translateX(0)":"translateX(-100%)",transition:"transform 0.25s ease",display:"flex",flexDirection:"column"}},React.createElement("div",{style:{padding:"20px 16px",borderBottom:"1px solid "+BR,display:"flex",alignItems:"center",gap:10}},React.createElement("div",{style:{width:36,height:36,borderRadius:10,background:"linear-gradient(135deg,"+P+","+PM+")",display:"flex",alignItems:"center",justifyContent:"center",fontSize:18}},"\uD83C\uDFE5"),React.createElement("div",null,React.createElement("div",{style:{fontSize:13,fontWeight:800,color:TX}},"Bharat Health"),React.createElement("div",{style:{fontSize:9,color:MT,fontWeight:600}},"Connect"))),React.createElement("div",{style:{flex:1,overflow:"auto",padding:"12px 8px"}},items.map(function(it){var isActive=active===it.id;return React.createElement("button",{key:it.id,onClick:function(){nav(it.id);onClose()},style:{width:"100%",display:"flex",alignItems:"center",gap:10,padding:"10px 12px",borderRadius:12,marginBottom:2,border:"none",background:isActive?A+"15":"transparent",color:isActive?A:SB,cursor:"pointer",fontSize:13,fontWeight:isActive?700:500,textAlign:"left",transition:"all 0.12s"}},React.createElement("span",{style:{fontSize:17}},it.i),it.l,isActive?React.createElement("div",{style:{marginLeft:"auto",width:5,height:5,borderRadius:"50%",background:A}}):null)})),React.createElement("div",{style:{padding:"12px 16px",borderTop:"1px solid "+BR,fontSize:10,color:MT}},"Governed by QCI \u2022 NABH Verified")));
}

/* ═══════════════════════════ MAIN APP ═══════════════════════════ */
export default function App(){
  var ss=useState("login"),screen=ss[0],setScreen=ss[1];
  var ts=useState("dashboard"),tab=ts[0],setTab=ts[1];
  var rs=useState(null),role=rs[0],setRole=rs[1];
  var ms=useState(false),menuOpen=ms[0],setMenuOpen=ms[1];

  var login=function(r){setRole(r);setScreen("app");setTab("dashboard")};
  var nav=function(t){setTab(t);setMenuOpen(false)};
  var logout=function(){setScreen("login");setRole(null);setTab("dashboard")};

  var renderScreen=function(){
    if(tab==="dashboard") return React.createElement(DashboardScreen,{role:role,nav:nav});
    if(tab==="hospitals") return React.createElement(HospitalListScreen,{nav:nav});
    if(tab.startsWith("hospital-")){var id=parseInt(tab.split("-")[1]);return React.createElement(HospitalDetailScreen,{id:id,nav:nav})}
    if(tab==="mvtfs") return React.createElement(MVTFScreen,{nav:nav});
    if(tab==="partners") return React.createElement(PartnerScreen);
    if(tab==="referrals") return React.createElement(ReferralScreen);
    if(tab==="grievances") return React.createElement(GrievanceScreen);
    if(tab==="onboarding") return React.createElement(OnboardingScreen);
    if(tab==="analytics") return React.createElement(AnalyticsScreen);
    if(tab==="profile") return React.createElement(ProfileScreen,{role:role,onLogout:logout});
    return React.createElement(DashboardScreen,{role:role,nav:nav});
  };

  if(screen==="login") return React.createElement(React.Fragment,null,React.createElement(Head,null,React.createElement("title",null,"Bharat Health Connect"),React.createElement("meta",{name:"description",content:"India's Medical Value Tourism Digital Platform"}),React.createElement("meta",{name:"viewport",content:"width=device-width, initial-scale=1"})),React.createElement("div",{style:{minHeight:"100vh",fontFamily:"'Segoe UI',system-ui,-apple-system,sans-serif"}},React.createElement(LoginScreen,{onLogin:login})));

  return React.createElement(React.Fragment,null,
    React.createElement(Head,null,React.createElement("title",null,"Bharat Health Connect"),React.createElement("meta",{name:"viewport",content:"width=device-width, initial-scale=1"})),
    React.createElement(Sidebar,{active:tab,nav:nav,role:role,open:menuOpen,onClose:function(){setMenuOpen(false)}}),
    React.createElement("div",{style:{minHeight:"100vh",fontFamily:"'Segoe UI',system-ui,-apple-system,sans-serif",background:BG}},
      React.createElement("div",{style:{position:"sticky",top:0,zIndex:50,background:CD,borderBottom:"1px solid "+BR,padding:"12px 20px",display:"flex",alignItems:"center",justifyContent:"space-between"}},
        React.createElement("div",{style:{display:"flex",alignItems:"center",gap:12}},
          React.createElement("button",{onClick:function(){setMenuOpen(true)},style:{background:"none",border:"none",cursor:"pointer",fontSize:20,padding:4}},"\u2630"),
          React.createElement("div",{style:{fontSize:15,fontWeight:800,color:P}},"Bharat Health Connect")),
        React.createElement("div",{style:{display:"flex",alignItems:"center",gap:8}},
          React.createElement("select",{value:role,onChange:function(e){setRole(e.target.value);setTab("dashboard")},style:{padding:"6px 10px",borderRadius:8,border:"1px solid "+BR,fontSize:11,fontWeight:600,color:P,cursor:"pointer",background:CD}},
            React.createElement("option",{value:"overseas"},"\uD83C\uDF0D Overseas Partner"),
            React.createElement("option",{value:"mvtf"},"\uD83E\uDD1D Indian MVTF"),
            React.createElement("option",{value:"hospital"},"\uD83C\uDFE5 Hospital"),
            React.createElement("option",{value:"admin"},"\uD83D\uDEE1\uFE0F QCI Admin")))),
      React.createElement("div",{style:{maxWidth:900,margin:"0 auto"}},renderScreen())));
}
